# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "chatnode"
client_id = "972970b2438bbd1a48b61d2645dd2cca"
application_url = "https://devoted-sports-combat-elected.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://devoted-sports-combat-elected.trycloudflare.com/auth/callback",
  "https://devoted-sports-combat-elected.trycloudflare.com/auth/shopify/callback",
  "https://devoted-sports-combat-elected.trycloudflare.com/api/auth/callback",
  "https://devoted-sports-combat-elected.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chatbit-dev-store.myshopify.com"
